{
    'name': 'Skilled Abilities',
    'category': 'Generic Modules/Human Resources',
    'author': 'GeoiWorks',
    'version': '17.0.1.0.2',
    'sequence': 3,
    'license': 'LGPL-3',
    'summary': 'Job Portal',
    'description': """Job Portal.""",
    'depends': ['website_hr_recruitment', 'contacts', 'website', 'hr_recruitment'],
    'data': [
        'security/ir.model.access.csv',
        'security/user_roles.xml',
        'views/hide_menus.xml',
        'views/all_jobs.xml',
        'views/job_details.xml',
        'views/apply_job.xml',
        'views/pricing.xml',
        'views/home.xml',
        'views/hr_job_inherit.xml',
        'views/application_submitted.xml',
        'views/hr_applicant_inherit.xml',
        'views/job_details_new.xml',
        'views/stepper_profile.xml',
        'views/stepper_profile_1.xml',
        'views/stepper_profile_2.xml',
        'views/signup_template.xml',
        'views/job_share.xml',
        'views/recruitment_inherit.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'job_portal/static/src/css/style.css',
            'job_portal/static/src/js/change_title.js',
        ],

        'web.assets_backend': [
            'job_portal/static/src/css/style.css',
            'job_portal/static/src/js/change_title.js',
        ],
    },
    'images': [],
    'application': True,
}